### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by zmija** [cortezaproject/corteza-webapp-auth#3]
**Describe the solution you'd like**
A list of external providers can be modified (content and amount-wise) so we need to find a way to display them in the same width.

![image](https://user-images.githubusercontent.com/8327569/60963449-17c3f300-a311-11e9-8721-096b18af0a07.png)

**Comment by tjerman** [comment]
https://github.com/cortezaproject/corteza-webapp-auth/commit/b4a2f502def326f391ab8fa413ba767ded447f47

![Screenshot from 2019-11-13 11-28-03](https://user-images.githubusercontent.com/12545711/68757182-c8b60380-060b-11ea-88c2-5943625e712c.png)
