### ISSUE TITLE
Google plus external provider has a broken image

### ISSUE THREAD

**Issue by tjerman** [cortezaproject/corteza-webapp-auth#5]
**Describe the bug**
Google plus external provider has a broken image

**To Reproduce**
Go to https://latest.cortezaproject.org/auth/login. Google plus's icon should not be there.

**Screenshots**
![Screenshot from 2019-07-21 18-39-41](https://user-images.githubusercontent.com/12545711/61594054-847b9f00-abe7-11e9-8a08-7caf9d3462ab.png)

**Desktop (please complete the following information):**
Ubuntu 19.04 - Google Chrome

**Additional context**
*External provider component*
![Screenshot from 2019-07-21 18-43-50](https://user-images.githubusercontent.com/12545711/61594058-8b0a1680-abe7-11e9-8c30-70f6f62103ee.png)

**Comment by zmija** [comment]
Added a comment to the code - I made a temporary solution but will be done properly once we migrate to Google instead of G+
