### ISSUE TITLE
Forgotten pw > missing string when user doesn't exist

### ISSUE THREAD

**Issue by zmija** [cortezaproject/corteza-webapp-auth#7]
If a user doesn't exist in the database, there's an error msg "system.repository.UserNotFound". The appropriate error msg is "Error: User doesn't exist"

tested on latest.cortezaproject.org

![image](https://user-images.githubusercontent.com/8327569/63714187-887f8a00-c841-11e9-84bd-f265832a75a2.png)

**Comment by tjerman** [comment]
@darh If I remember correctly we said, that messages from API will be translated; is this still the case or?

**Comment by darh** [comment]
Not the case.

All error messages will be typed (in direction of `system.repositorty.UserNotFound`).
Until then, please make a workaround to handle this.

**Comment by tjerman** [comment]
Understood

**Comment by zmija** [comment]
@tjerman please fix this (it's been 3 months already), thanks.

**Comment by tjerman** [comment]
![Screenshot from 2019-11-13 10-58-18](https://user-images.githubusercontent.com/12545711/68753050-a1a80380-0604-11ea-9d9c-2cde859b5ad3.png)
